// ISO 3166-1 alpha-2 codes for UN member + observer states.
// All seeded as LOCKED — they get flipped to UNLOCKED as songs are curated for them.
export const countries: { isoCode: string; name: string; region: string; latitude: number; longitude: number }[] = [
  { isoCode: 'AF', name: 'Afghanistan', region: 'Asia', latitude: 33, longitude: 65 },
  { isoCode: 'AL', name: 'Albania', region: 'Europe', latitude: 41, longitude: 20 },
  { isoCode: 'DZ', name: 'Algeria', region: 'Africa', latitude: 28, longitude: 3 },
  { isoCode: 'AD', name: 'Andorra', region: 'Europe', latitude: 42.5, longitude: 1.5 },
  { isoCode: 'AO', name: 'Angola', region: 'Africa', latitude: -12.5, longitude: 18.5 },
  { isoCode: 'AG', name: 'Antigua and Barbuda', region: 'Americas', latitude: 17.05, longitude: -61.8 },
  { isoCode: 'AR', name: 'Argentina', region: 'Americas', latitude: -34, longitude: -64 },
  { isoCode: 'AM', name: 'Armenia', region: 'Asia', latitude: 40, longitude: 45 },
  { isoCode: 'AU', name: 'Australia', region: 'Oceania', latitude: -27, longitude: 133 },
  { isoCode: 'AT', name: 'Austria', region: 'Europe', latitude: 47.33333333, longitude: 13.33333333 },
  { isoCode: 'AZ', name: 'Azerbaijan', region: 'Asia', latitude: 40.5, longitude: 47.5 },
  { isoCode: 'BS', name: 'Bahamas', region: 'Americas', latitude: 24.25, longitude: -76 },
  { isoCode: 'BH', name: 'Bahrain', region: 'Asia', latitude: 26, longitude: 50.55 },
  { isoCode: 'BD', name: 'Bangladesh', region: 'Asia', latitude: 24, longitude: 90 },
  { isoCode: 'BB', name: 'Barbados', region: 'Americas', latitude: 13.16666666, longitude: -59.53333333 },
  { isoCode: 'BY', name: 'Belarus', region: 'Europe', latitude: 53, longitude: 28 },
  { isoCode: 'BE', name: 'Belgium', region: 'Europe', latitude: 50.83333333, longitude: 4 },
  { isoCode: 'BZ', name: 'Belize', region: 'Americas', latitude: 17.25, longitude: -88.75 },
  { isoCode: 'BJ', name: 'Benin', region: 'Africa', latitude: 9.5, longitude: 2.25 },
  { isoCode: 'BT', name: 'Bhutan', region: 'Asia', latitude: 27.5, longitude: 90.5 },
  { isoCode: 'BO', name: 'Bolivia', region: 'Americas', latitude: -17, longitude: -65 },
  { isoCode: 'BA', name: 'Bosnia and Herzegovina', region: 'Europe', latitude: 44, longitude: 18 },
  { isoCode: 'BW', name: 'Botswana', region: 'Africa', latitude: -22, longitude: 24 },
  { isoCode: 'BR', name: 'Brazil', region: 'Americas', latitude: -10, longitude: -55 },
  { isoCode: 'BN', name: 'Brunei', region: 'Asia', latitude: 4.5, longitude: 114.66666666 },
  { isoCode: 'BG', name: 'Bulgaria', region: 'Europe', latitude: 43, longitude: 25 },
  { isoCode: 'BF', name: 'Burkina Faso', region: 'Africa', latitude: 13, longitude: -2 },
  { isoCode: 'BI', name: 'Burundi', region: 'Africa', latitude: -3.5, longitude: 30 },
  { isoCode: 'CV', name: 'Cabo Verde', region: 'Africa', latitude: 16, longitude: -24 },
  { isoCode: 'KH', name: 'Cambodia', region: 'Asia', latitude: 13, longitude: 105 },
  { isoCode: 'CM', name: 'Cameroon', region: 'Africa', latitude: 6, longitude: 12 },
  { isoCode: 'CA', name: 'Canada', region: 'Americas', latitude: 60, longitude: -95 },
  { isoCode: 'CF', name: 'Central African Republic', region: 'Africa', latitude: 7, longitude: 21 },
  { isoCode: 'TD', name: 'Chad', region: 'Africa', latitude: 15, longitude: 19 },
  { isoCode: 'CL', name: 'Chile', region: 'Americas', latitude: -30, longitude: -71 },
  { isoCode: 'CN', name: 'China', region: 'Asia', latitude: 35, longitude: 105 },
  { isoCode: 'CO', name: 'Colombia', region: 'Americas', latitude: 4, longitude: -72 },
  { isoCode: 'KM', name: 'Comoros', region: 'Africa', latitude: -12.16666666, longitude: 44.25 },
  { isoCode: 'CG', name: 'Congo', region: 'Africa', latitude: -1, longitude: 15 },
  { isoCode: 'CD', name: 'Congo (DRC)', region: 'Africa', latitude: 0, longitude: 25 },
  { isoCode: 'CR', name: 'Costa Rica', region: 'Americas', latitude: 10, longitude: -84 },
  { isoCode: 'CI', name: "Cote d'Ivoire", region: 'Africa', latitude: 8, longitude: -5 },
  { isoCode: 'HR', name: 'Croatia', region: 'Europe', latitude: 45.16666666, longitude: 15.5 },
  { isoCode: 'CU', name: 'Cuba', region: 'Americas', latitude: 21.5, longitude: -80 },
  { isoCode: 'CY', name: 'Cyprus', region: 'Europe', latitude: 35, longitude: 33 },
  { isoCode: 'CZ', name: 'Czechia', region: 'Europe', latitude: 49.75, longitude: 15.5 },
  { isoCode: 'DK', name: 'Denmark', region: 'Europe', latitude: 56, longitude: 10 },
  { isoCode: 'DJ', name: 'Djibouti', region: 'Africa', latitude: 11.5, longitude: 43 },
  { isoCode: 'DM', name: 'Dominica', region: 'Americas', latitude: 15.41666666, longitude: -61.33333333 },
  { isoCode: 'DO', name: 'Dominican Republic', region: 'Americas', latitude: 19, longitude: -70.66666666 },
  { isoCode: 'EC', name: 'Ecuador', region: 'Americas', latitude: -2, longitude: -77.5 },
  { isoCode: 'EG', name: 'Egypt', region: 'Africa', latitude: 27, longitude: 30 },
  { isoCode: 'SV', name: 'El Salvador', region: 'Americas', latitude: 13.83333333, longitude: -88.91666666 },
  { isoCode: 'GQ', name: 'Equatorial Guinea', region: 'Africa', latitude: 2, longitude: 10 },
  { isoCode: 'ER', name: 'Eritrea', region: 'Africa', latitude: 15, longitude: 39 },
  { isoCode: 'EE', name: 'Estonia', region: 'Europe', latitude: 59, longitude: 26 },
  { isoCode: 'SZ', name: 'Eswatini', region: 'Africa', latitude: -26.5, longitude: 31.5 },
  { isoCode: 'ET', name: 'Ethiopia', region: 'Africa', latitude: 8, longitude: 38 },
  { isoCode: 'FJ', name: 'Fiji', region: 'Oceania', latitude: -18, longitude: 175 },
  { isoCode: 'FI', name: 'Finland', region: 'Europe', latitude: 64, longitude: 26 },
  { isoCode: 'FR', name: 'France', region: 'Europe', latitude: 46, longitude: 2 },
  { isoCode: 'GA', name: 'Gabon', region: 'Africa', latitude: -1, longitude: 11.75 },
  { isoCode: 'GM', name: 'Gambia', region: 'Africa', latitude: 13.46666666, longitude: -16.56666666 },
  { isoCode: 'GE', name: 'Georgia', region: 'Asia', latitude: 42, longitude: 43.5 },
  { isoCode: 'DE', name: 'Germany', region: 'Europe', latitude: 51, longitude: 9 },
  { isoCode: 'GH', name: 'Ghana', region: 'Africa', latitude: 8, longitude: -2 },
  { isoCode: 'GR', name: 'Greece', region: 'Europe', latitude: 39, longitude: 22 },
  { isoCode: 'GD', name: 'Grenada', region: 'Americas', latitude: 12.11666666, longitude: -61.66666666 },
  { isoCode: 'GT', name: 'Guatemala', region: 'Americas', latitude: 15.5, longitude: -90.25 },
  { isoCode: 'GN', name: 'Guinea', region: 'Africa', latitude: 11, longitude: -10 },
  { isoCode: 'GW', name: 'Guinea-Bissau', region: 'Africa', latitude: 12, longitude: -15 },
  { isoCode: 'GY', name: 'Guyana', region: 'Americas', latitude: 5, longitude: -59 },
  { isoCode: 'HT', name: 'Haiti', region: 'Americas', latitude: 19, longitude: -72.41666666 },
  { isoCode: 'HN', name: 'Honduras', region: 'Americas', latitude: 15, longitude: -86.5 },
  { isoCode: 'HU', name: 'Hungary', region: 'Europe', latitude: 47, longitude: 20 },
  { isoCode: 'IS', name: 'Iceland', region: 'Europe', latitude: 65, longitude: -18 },
  { isoCode: 'IN', name: 'India', region: 'Asia', latitude: 20, longitude: 77 },
  { isoCode: 'ID', name: 'Indonesia', region: 'Asia', latitude: -5, longitude: 120 },
  { isoCode: 'IR', name: 'Iran', region: 'Asia', latitude: 32, longitude: 53 },
  { isoCode: 'IQ', name: 'Iraq', region: 'Asia', latitude: 33, longitude: 44 },
  { isoCode: 'IE', name: 'Ireland', region: 'Europe', latitude: 53, longitude: -8 },
  { isoCode: 'IL', name: 'Israel', region: 'Asia', latitude: 31.47, longitude: 35.13 },
  { isoCode: 'IT', name: 'Italy', region: 'Europe', latitude: 42.83333333, longitude: 12.83333333 },
  { isoCode: 'JM', name: 'Jamaica', region: 'Americas', latitude: 18.25, longitude: -77.5 },
  { isoCode: 'JP', name: 'Japan', region: 'Asia', latitude: 36, longitude: 138 },
  { isoCode: 'JO', name: 'Jordan', region: 'Asia', latitude: 31, longitude: 36 },
  { isoCode: 'KZ', name: 'Kazakhstan', region: 'Asia', latitude: 48, longitude: 68 },
  { isoCode: 'KE', name: 'Kenya', region: 'Africa', latitude: 1, longitude: 38 },
  { isoCode: 'KI', name: 'Kiribati', region: 'Oceania', latitude: 1.41666666, longitude: 173 },
  { isoCode: 'KP', name: 'Korea (North)', region: 'Asia', latitude: 40, longitude: 127 },
  { isoCode: 'KR', name: 'Korea (South)', region: 'Asia', latitude: 37, longitude: 127.5 },
  { isoCode: 'KW', name: 'Kuwait', region: 'Asia', latitude: 29.5, longitude: 45.75 },
  { isoCode: 'KG', name: 'Kyrgyzstan', region: 'Asia', latitude: 41, longitude: 75 },
  { isoCode: 'LA', name: 'Laos', region: 'Asia', latitude: 18, longitude: 105 },
  { isoCode: 'LV', name: 'Latvia', region: 'Europe', latitude: 57, longitude: 25 },
  { isoCode: 'LB', name: 'Lebanon', region: 'Asia', latitude: 33.83333333, longitude: 35.83333333 },
  { isoCode: 'LS', name: 'Lesotho', region: 'Africa', latitude: -29.5, longitude: 28.5 },
  { isoCode: 'LR', name: 'Liberia', region: 'Africa', latitude: 6.5, longitude: -9.5 },
  { isoCode: 'LY', name: 'Libya', region: 'Africa', latitude: 25, longitude: 17 },
  { isoCode: 'LI', name: 'Liechtenstein', region: 'Europe', latitude: 47.26666666, longitude: 9.53333333 },
  { isoCode: 'LT', name: 'Lithuania', region: 'Europe', latitude: 56, longitude: 24 },
  { isoCode: 'LU', name: 'Luxembourg', region: 'Europe', latitude: 49.75, longitude: 6.16666666 },
  { isoCode: 'MG', name: 'Madagascar', region: 'Africa', latitude: -20, longitude: 47 },
  { isoCode: 'MW', name: 'Malawi', region: 'Africa', latitude: -13.5, longitude: 34 },
  { isoCode: 'MY', name: 'Malaysia', region: 'Asia', latitude: 2.5, longitude: 112.5 },
  { isoCode: 'MV', name: 'Maldives', region: 'Asia', latitude: 3.25, longitude: 73 },
  { isoCode: 'ML', name: 'Mali', region: 'Africa', latitude: 17, longitude: -4 },
  { isoCode: 'MT', name: 'Malta', region: 'Europe', latitude: 35.83333333, longitude: 14.58333333 },
  { isoCode: 'MH', name: 'Marshall Islands', region: 'Oceania', latitude: 9, longitude: 168 },
  { isoCode: 'MR', name: 'Mauritania', region: 'Africa', latitude: 20, longitude: -12 },
  { isoCode: 'MU', name: 'Mauritius', region: 'Africa', latitude: -20.28333333, longitude: 57.55 },
  { isoCode: 'MX', name: 'Mexico', region: 'Americas', latitude: 23, longitude: -102 },
  { isoCode: 'FM', name: 'Micronesia', region: 'Oceania', latitude: 6.91666666, longitude: 158.25 },
  { isoCode: 'MD', name: 'Moldova', region: 'Europe', latitude: 47, longitude: 29 },
  { isoCode: 'MC', name: 'Monaco', region: 'Europe', latitude: 43.73333333, longitude: 7.4 },
  { isoCode: 'MN', name: 'Mongolia', region: 'Asia', latitude: 46, longitude: 105 },
  { isoCode: 'ME', name: 'Montenegro', region: 'Europe', latitude: 42.5, longitude: 19.3 },
  { isoCode: 'MA', name: 'Morocco', region: 'Africa', latitude: 32, longitude: -5 },
  { isoCode: 'MZ', name: 'Mozambique', region: 'Africa', latitude: -18.25, longitude: 35 },
  { isoCode: 'MM', name: 'Myanmar', region: 'Asia', latitude: 22, longitude: 98 },
  { isoCode: 'NA', name: 'Namibia', region: 'Africa', latitude: -22, longitude: 17 },
  { isoCode: 'NR', name: 'Nauru', region: 'Oceania', latitude: -0.53333333, longitude: 166.91666666 },
  { isoCode: 'NP', name: 'Nepal', region: 'Asia', latitude: 28, longitude: 84 },
  { isoCode: 'NL', name: 'Netherlands', region: 'Europe', latitude: 52.5, longitude: 5.75 },
  { isoCode: 'NZ', name: 'New Zealand', region: 'Oceania', latitude: -41, longitude: 174 },
  { isoCode: 'NI', name: 'Nicaragua', region: 'Americas', latitude: 13, longitude: -85 },
  { isoCode: 'NE', name: 'Niger', region: 'Africa', latitude: 16, longitude: 8 },
  { isoCode: 'NG', name: 'Nigeria', region: 'Africa', latitude: 10, longitude: 8 },
  { isoCode: 'MK', name: 'North Macedonia', region: 'Europe', latitude: 41.83333333, longitude: 22 },
  { isoCode: 'NO', name: 'Norway', region: 'Europe', latitude: 62, longitude: 10 },
  { isoCode: 'OM', name: 'Oman', region: 'Asia', latitude: 21, longitude: 57 },
  { isoCode: 'PK', name: 'Pakistan', region: 'Asia', latitude: 30, longitude: 70 },
  { isoCode: 'PW', name: 'Palau', region: 'Oceania', latitude: 7.5, longitude: 134.5 },
  { isoCode: 'PS', name: 'Palestine', region: 'Asia', latitude: 31.9, longitude: 35.2 },
  { isoCode: 'PA', name: 'Panama', region: 'Americas', latitude: 9, longitude: -80 },
  { isoCode: 'PG', name: 'Papua New Guinea', region: 'Oceania', latitude: -6, longitude: 147 },
  { isoCode: 'PY', name: 'Paraguay', region: 'Americas', latitude: -23, longitude: -58 },
  { isoCode: 'PE', name: 'Peru', region: 'Americas', latitude: -10, longitude: -76 },
  { isoCode: 'PH', name: 'Philippines', region: 'Asia', latitude: 13, longitude: 122 },
  { isoCode: 'PL', name: 'Poland', region: 'Europe', latitude: 52, longitude: 20 },
  { isoCode: 'PT', name: 'Portugal', region: 'Europe', latitude: 39.5, longitude: -8 },
  { isoCode: 'QA', name: 'Qatar', region: 'Asia', latitude: 25.5, longitude: 51.25 },
  { isoCode: 'RO', name: 'Romania', region: 'Europe', latitude: 46, longitude: 25 },
  { isoCode: 'RU', name: 'Russia', region: 'Europe', latitude: 60, longitude: 100 },
  { isoCode: 'RW', name: 'Rwanda', region: 'Africa', latitude: -2, longitude: 30 },
  { isoCode: 'KN', name: 'Saint Kitts and Nevis', region: 'Americas', latitude: 17.33333333, longitude: -62.75 },
  { isoCode: 'LC', name: 'Saint Lucia', region: 'Americas', latitude: 13.88333333, longitude: -60.96666666 },
  { isoCode: 'VC', name: 'Saint Vincent and the Grenadines', region: 'Americas', latitude: 13.25, longitude: -61.2 },
  { isoCode: 'WS', name: 'Samoa', region: 'Oceania', latitude: -13.58333333, longitude: -172.33333333 },
  { isoCode: 'SM', name: 'San Marino', region: 'Europe', latitude: 43.76666666, longitude: 12.41666666 },
  { isoCode: 'ST', name: 'Sao Tome and Principe', region: 'Africa', latitude: 1, longitude: 7 },
  { isoCode: 'SA', name: 'Saudi Arabia', region: 'Asia', latitude: 25, longitude: 45 },
  { isoCode: 'SN', name: 'Senegal', region: 'Africa', latitude: 14, longitude: -14 },
  { isoCode: 'RS', name: 'Serbia', region: 'Europe', latitude: 44, longitude: 21 },
  { isoCode: 'SC', name: 'Seychelles', region: 'Africa', latitude: -4.58333333, longitude: 55.66666666 },
  { isoCode: 'SL', name: 'Sierra Leone', region: 'Africa', latitude: 8.5, longitude: -11.5 },
  { isoCode: 'SG', name: 'Singapore', region: 'Asia', latitude: 1.36666666, longitude: 103.8 },
  { isoCode: 'SK', name: 'Slovakia', region: 'Europe', latitude: 48.66666666, longitude: 19.5 },
  { isoCode: 'SI', name: 'Slovenia', region: 'Europe', latitude: 46.11666666, longitude: 14.81666666 },
  { isoCode: 'SB', name: 'Solomon Islands', region: 'Oceania', latitude: -8, longitude: 159 },
  { isoCode: 'SO', name: 'Somalia', region: 'Africa', latitude: 10, longitude: 49 },
  { isoCode: 'ZA', name: 'South Africa', region: 'Africa', latitude: -29, longitude: 24 },
  { isoCode: 'SS', name: 'South Sudan', region: 'Africa', latitude: 7, longitude: 30 },
  { isoCode: 'ES', name: 'Spain', region: 'Europe', latitude: 40, longitude: -4 },
  { isoCode: 'LK', name: 'Sri Lanka', region: 'Asia', latitude: 7, longitude: 81 },
  { isoCode: 'SD', name: 'Sudan', region: 'Africa', latitude: 15, longitude: 30 },
  { isoCode: 'SR', name: 'Suriname', region: 'Americas', latitude: 4, longitude: -56 },
  { isoCode: 'SE', name: 'Sweden', region: 'Europe', latitude: 62, longitude: 15 },
  { isoCode: 'CH', name: 'Switzerland', region: 'Europe', latitude: 47, longitude: 8 },
  { isoCode: 'SY', name: 'Syria', region: 'Asia', latitude: 35, longitude: 38 },
  { isoCode: 'TJ', name: 'Tajikistan', region: 'Asia', latitude: 39, longitude: 71 },
  { isoCode: 'TZ', name: 'Tanzania', region: 'Africa', latitude: -6, longitude: 35 },
  { isoCode: 'TH', name: 'Thailand', region: 'Asia', latitude: 15, longitude: 100 },
  { isoCode: 'TL', name: 'Timor-Leste', region: 'Asia', latitude: -8.83333333, longitude: 125.91666666 },
  { isoCode: 'TG', name: 'Togo', region: 'Africa', latitude: 8, longitude: 1.16666666 },
  { isoCode: 'TO', name: 'Tonga', region: 'Oceania', latitude: -20, longitude: -175 },
  { isoCode: 'TT', name: 'Trinidad and Tobago', region: 'Americas', latitude: 11, longitude: -61 },
  { isoCode: 'TN', name: 'Tunisia', region: 'Africa', latitude: 34, longitude: 9 },
  { isoCode: 'TR', name: 'Turkey', region: 'Asia', latitude: 39, longitude: 35 },
  { isoCode: 'TM', name: 'Turkmenistan', region: 'Asia', latitude: 40, longitude: 60 },
  { isoCode: 'TV', name: 'Tuvalu', region: 'Oceania', latitude: -8, longitude: 178 },
  { isoCode: 'UG', name: 'Uganda', region: 'Africa', latitude: 1, longitude: 32 },
  { isoCode: 'UA', name: 'Ukraine', region: 'Europe', latitude: 49, longitude: 32 },
  { isoCode: 'AE', name: 'United Arab Emirates', region: 'Asia', latitude: 24, longitude: 54 },
  { isoCode: 'GB', name: 'United Kingdom', region: 'Europe', latitude: 54, longitude: -2 },
  { isoCode: 'US', name: 'United States', region: 'Americas', latitude: 38, longitude: -97 },
  { isoCode: 'UY', name: 'Uruguay', region: 'Americas', latitude: -33, longitude: -56 },
  { isoCode: 'UZ', name: 'Uzbekistan', region: 'Asia', latitude: 41, longitude: 64 },
  { isoCode: 'VU', name: 'Vanuatu', region: 'Oceania', latitude: -16, longitude: 167 },
  { isoCode: 'VA', name: 'Vatican City', region: 'Europe', latitude: 41.9, longitude: 12.45 },
  { isoCode: 'VE', name: 'Venezuela', region: 'Americas', latitude: 8, longitude: -66 },
  { isoCode: 'VN', name: 'Vietnam', region: 'Asia', latitude: 16.16666666, longitude: 107.83333333 },
  { isoCode: 'YE', name: 'Yemen', region: 'Asia', latitude: 15, longitude: 48 },
  { isoCode: 'ZM', name: 'Zambia', region: 'Africa', latitude: -15, longitude: 30 },
  { isoCode: 'ZW', name: 'Zimbabwe', region: 'Africa', latitude: -20, longitude: 30 },
]
