// ISO 3166-1 alpha-2 codes for UN member + observer states.
// All seeded as LOCKED — they get flipped to UNLOCKED as songs are curated for them.
export const countries: { isoCode: string; name: string; region: string }[] = [
  { isoCode: 'AF', name: 'Afghanistan', region: 'Asia' },
  { isoCode: 'AL', name: 'Albania', region: 'Europe' },
  { isoCode: 'DZ', name: 'Algeria', region: 'Africa' },
  { isoCode: 'AD', name: 'Andorra', region: 'Europe' },
  { isoCode: 'AO', name: 'Angola', region: 'Africa' },
  { isoCode: 'AG', name: 'Antigua and Barbuda', region: 'Americas' },
  { isoCode: 'AR', name: 'Argentina', region: 'Americas' },
  { isoCode: 'AM', name: 'Armenia', region: 'Asia' },
  { isoCode: 'AU', name: 'Australia', region: 'Oceania' },
  { isoCode: 'AT', name: 'Austria', region: 'Europe' },
  { isoCode: 'AZ', name: 'Azerbaijan', region: 'Asia' },
  { isoCode: 'BS', name: 'Bahamas', region: 'Americas' },
  { isoCode: 'BH', name: 'Bahrain', region: 'Asia' },
  { isoCode: 'BD', name: 'Bangladesh', region: 'Asia' },
  { isoCode: 'BB', name: 'Barbados', region: 'Americas' },
  { isoCode: 'BY', name: 'Belarus', region: 'Europe' },
  { isoCode: 'BE', name: 'Belgium', region: 'Europe' },
  { isoCode: 'BZ', name: 'Belize', region: 'Americas' },
  { isoCode: 'BJ', name: 'Benin', region: 'Africa' },
  { isoCode: 'BT', name: 'Bhutan', region: 'Asia' },
  { isoCode: 'BO', name: 'Bolivia', region: 'Americas' },
  { isoCode: 'BA', name: 'Bosnia and Herzegovina', region: 'Europe' },
  { isoCode: 'BW', name: 'Botswana', region: 'Africa' },
  { isoCode: 'BR', name: 'Brazil', region: 'Americas' },
  { isoCode: 'BN', name: 'Brunei', region: 'Asia' },
  { isoCode: 'BG', name: 'Bulgaria', region: 'Europe' },
  { isoCode: 'BF', name: 'Burkina Faso', region: 'Africa' },
  { isoCode: 'BI', name: 'Burundi', region: 'Africa' },
  { isoCode: 'CV', name: 'Cabo Verde', region: 'Africa' },
  { isoCode: 'KH', name: 'Cambodia', region: 'Asia' },
  { isoCode: 'CM', name: 'Cameroon', region: 'Africa' },
  { isoCode: 'CA', name: 'Canada', region: 'Americas' },
  { isoCode: 'CF', name: 'Central African Republic', region: 'Africa' },
  { isoCode: 'TD', name: 'Chad', region: 'Africa' },
  { isoCode: 'CL', name: 'Chile', region: 'Americas' },
  { isoCode: 'CN', name: 'China', region: 'Asia' },
  { isoCode: 'CO', name: 'Colombia', region: 'Americas' },
  { isoCode: 'KM', name: 'Comoros', region: 'Africa' },
  { isoCode: 'CG', name: 'Congo', region: 'Africa' },
  { isoCode: 'CD', name: 'Congo (DRC)', region: 'Africa' },
  { isoCode: 'CR', name: 'Costa Rica', region: 'Americas' },
  { isoCode: 'CI', name: "Cote d'Ivoire", region: 'Africa' },
  { isoCode: 'HR', name: 'Croatia', region: 'Europe' },
  { isoCode: 'CU', name: 'Cuba', region: 'Americas' },
  { isoCode: 'CY', name: 'Cyprus', region: 'Europe' },
  { isoCode: 'CZ', name: 'Czechia', region: 'Europe' },
  { isoCode: 'DK', name: 'Denmark', region: 'Europe' },
  { isoCode: 'DJ', name: 'Djibouti', region: 'Africa' },
  { isoCode: 'DM', name: 'Dominica', region: 'Americas' },
  { isoCode: 'DO', name: 'Dominican Republic', region: 'Americas' },
  { isoCode: 'EC', name: 'Ecuador', region: 'Americas' },
  { isoCode: 'EG', name: 'Egypt', region: 'Africa' },
  { isoCode: 'SV', name: 'El Salvador', region: 'Americas' },
  { isoCode: 'GQ', name: 'Equatorial Guinea', region: 'Africa' },
  { isoCode: 'ER', name: 'Eritrea', region: 'Africa' },
  { isoCode: 'EE', name: 'Estonia', region: 'Europe' },
  { isoCode: 'SZ', name: 'Eswatini', region: 'Africa' },
  { isoCode: 'ET', name: 'Ethiopia', region: 'Africa' },
  { isoCode: 'FJ', name: 'Fiji', region: 'Oceania' },
  { isoCode: 'FI', name: 'Finland', region: 'Europe' },
  { isoCode: 'FR', name: 'France', region: 'Europe' },
  { isoCode: 'GA', name: 'Gabon', region: 'Africa' },
  { isoCode: 'GM', name: 'Gambia', region: 'Africa' },
  { isoCode: 'GE', name: 'Georgia', region: 'Asia' },
  { isoCode: 'DE', name: 'Germany', region: 'Europe' },
  { isoCode: 'GH', name: 'Ghana', region: 'Africa' },
  { isoCode: 'GR', name: 'Greece', region: 'Europe' },
  { isoCode: 'GD', name: 'Grenada', region: 'Americas' },
  { isoCode: 'GT', name: 'Guatemala', region: 'Americas' },
  { isoCode: 'GN', name: 'Guinea', region: 'Africa' },
  { isoCode: 'GW', name: 'Guinea-Bissau', region: 'Africa' },
  { isoCode: 'GY', name: 'Guyana', region: 'Americas' },
  { isoCode: 'HT', name: 'Haiti', region: 'Americas' },
  { isoCode: 'HN', name: 'Honduras', region: 'Americas' },
  { isoCode: 'HU', name: 'Hungary', region: 'Europe' },
  { isoCode: 'IS', name: 'Iceland', region: 'Europe' },
  { isoCode: 'IN', name: 'India', region: 'Asia' },
  { isoCode: 'ID', name: 'Indonesia', region: 'Asia' },
  { isoCode: 'IR', name: 'Iran', region: 'Asia' },
  { isoCode: 'IQ', name: 'Iraq', region: 'Asia' },
  { isoCode: 'IE', name: 'Ireland', region: 'Europe' },
  { isoCode: 'IL', name: 'Israel', region: 'Asia' },
  { isoCode: 'IT', name: 'Italy', region: 'Europe' },
  { isoCode: 'JM', name: 'Jamaica', region: 'Americas' },
  { isoCode: 'JP', name: 'Japan', region: 'Asia' },
  { isoCode: 'JO', name: 'Jordan', region: 'Asia' },
  { isoCode: 'KZ', name: 'Kazakhstan', region: 'Asia' },
  { isoCode: 'KE', name: 'Kenya', region: 'Africa' },
  { isoCode: 'KI', name: 'Kiribati', region: 'Oceania' },
  { isoCode: 'KP', name: 'Korea (North)', region: 'Asia' },
  { isoCode: 'KR', name: 'Korea (South)', region: 'Asia' },
  { isoCode: 'KW', name: 'Kuwait', region: 'Asia' },
  { isoCode: 'KG', name: 'Kyrgyzstan', region: 'Asia' },
  { isoCode: 'LA', name: 'Laos', region: 'Asia' },
  { isoCode: 'LV', name: 'Latvia', region: 'Europe' },
  { isoCode: 'LB', name: 'Lebanon', region: 'Asia' },
  { isoCode: 'LS', name: 'Lesotho', region: 'Africa' },
  { isoCode: 'LR', name: 'Liberia', region: 'Africa' },
  { isoCode: 'LY', name: 'Libya', region: 'Africa' },
  { isoCode: 'LI', name: 'Liechtenstein', region: 'Europe' },
  { isoCode: 'LT', name: 'Lithuania', region: 'Europe' },
  { isoCode: 'LU', name: 'Luxembourg', region: 'Europe' },
  { isoCode: 'MG', name: 'Madagascar', region: 'Africa' },
  { isoCode: 'MW', name: 'Malawi', region: 'Africa' },
  { isoCode: 'MY', name: 'Malaysia', region: 'Asia' },
  { isoCode: 'MV', name: 'Maldives', region: 'Asia' },
  { isoCode: 'ML', name: 'Mali', region: 'Africa' },
  { isoCode: 'MT', name: 'Malta', region: 'Europe' },
  { isoCode: 'MH', name: 'Marshall Islands', region: 'Oceania' },
  { isoCode: 'MR', name: 'Mauritania', region: 'Africa' },
  { isoCode: 'MU', name: 'Mauritius', region: 'Africa' },
  { isoCode: 'MX', name: 'Mexico', region: 'Americas' },
  { isoCode: 'FM', name: 'Micronesia', region: 'Oceania' },
  { isoCode: 'MD', name: 'Moldova', region: 'Europe' },
  { isoCode: 'MC', name: 'Monaco', region: 'Europe' },
  { isoCode: 'MN', name: 'Mongolia', region: 'Asia' },
  { isoCode: 'ME', name: 'Montenegro', region: 'Europe' },
  { isoCode: 'MA', name: 'Morocco', region: 'Africa' },
  { isoCode: 'MZ', name: 'Mozambique', region: 'Africa' },
  { isoCode: 'MM', name: 'Myanmar', region: 'Asia' },
  { isoCode: 'NA', name: 'Namibia', region: 'Africa' },
  { isoCode: 'NR', name: 'Nauru', region: 'Oceania' },
  { isoCode: 'NP', name: 'Nepal', region: 'Asia' },
  { isoCode: 'NL', name: 'Netherlands', region: 'Europe' },
  { isoCode: 'NZ', name: 'New Zealand', region: 'Oceania' },
  { isoCode: 'NI', name: 'Nicaragua', region: 'Americas' },
  { isoCode: 'NE', name: 'Niger', region: 'Africa' },
  { isoCode: 'NG', name: 'Nigeria', region: 'Africa' },
  { isoCode: 'MK', name: 'North Macedonia', region: 'Europe' },
  { isoCode: 'NO', name: 'Norway', region: 'Europe' },
  { isoCode: 'OM', name: 'Oman', region: 'Asia' },
  { isoCode: 'PK', name: 'Pakistan', region: 'Asia' },
  { isoCode: 'PW', name: 'Palau', region: 'Oceania' },
  { isoCode: 'PS', name: 'Palestine', region: 'Asia' },
  { isoCode: 'PA', name: 'Panama', region: 'Americas' },
  { isoCode: 'PG', name: 'Papua New Guinea', region: 'Oceania' },
  { isoCode: 'PY', name: 'Paraguay', region: 'Americas' },
  { isoCode: 'PE', name: 'Peru', region: 'Americas' },
  { isoCode: 'PH', name: 'Philippines', region: 'Asia' },
  { isoCode: 'PL', name: 'Poland', region: 'Europe' },
  { isoCode: 'PT', name: 'Portugal', region: 'Europe' },
  { isoCode: 'QA', name: 'Qatar', region: 'Asia' },
  { isoCode: 'RO', name: 'Romania', region: 'Europe' },
  { isoCode: 'RU', name: 'Russia', region: 'Europe' },
  { isoCode: 'RW', name: 'Rwanda', region: 'Africa' },
  { isoCode: 'KN', name: 'Saint Kitts and Nevis', region: 'Americas' },
  { isoCode: 'LC', name: 'Saint Lucia', region: 'Americas' },
  { isoCode: 'VC', name: 'Saint Vincent and the Grenadines', region: 'Americas' },
  { isoCode: 'WS', name: 'Samoa', region: 'Oceania' },
  { isoCode: 'SM', name: 'San Marino', region: 'Europe' },
  { isoCode: 'ST', name: 'Sao Tome and Principe', region: 'Africa' },
  { isoCode: 'SA', name: 'Saudi Arabia', region: 'Asia' },
  { isoCode: 'SN', name: 'Senegal', region: 'Africa' },
  { isoCode: 'RS', name: 'Serbia', region: 'Europe' },
  { isoCode: 'SC', name: 'Seychelles', region: 'Africa' },
  { isoCode: 'SL', name: 'Sierra Leone', region: 'Africa' },
  { isoCode: 'SG', name: 'Singapore', region: 'Asia' },
  { isoCode: 'SK', name: 'Slovakia', region: 'Europe' },
  { isoCode: 'SI', name: 'Slovenia', region: 'Europe' },
  { isoCode: 'SB', name: 'Solomon Islands', region: 'Oceania' },
  { isoCode: 'SO', name: 'Somalia', region: 'Africa' },
  { isoCode: 'ZA', name: 'South Africa', region: 'Africa' },
  { isoCode: 'SS', name: 'South Sudan', region: 'Africa' },
  { isoCode: 'ES', name: 'Spain', region: 'Europe' },
  { isoCode: 'LK', name: 'Sri Lanka', region: 'Asia' },
  { isoCode: 'SD', name: 'Sudan', region: 'Africa' },
  { isoCode: 'SR', name: 'Suriname', region: 'Americas' },
  { isoCode: 'SE', name: 'Sweden', region: 'Europe' },
  { isoCode: 'CH', name: 'Switzerland', region: 'Europe' },
  { isoCode: 'SY', name: 'Syria', region: 'Asia' },
  { isoCode: 'TJ', name: 'Tajikistan', region: 'Asia' },
  { isoCode: 'TZ', name: 'Tanzania', region: 'Africa' },
  { isoCode: 'TH', name: 'Thailand', region: 'Asia' },
  { isoCode: 'TL', name: 'Timor-Leste', region: 'Asia' },
  { isoCode: 'TG', name: 'Togo', region: 'Africa' },
  { isoCode: 'TO', name: 'Tonga', region: 'Oceania' },
  { isoCode: 'TT', name: 'Trinidad and Tobago', region: 'Americas' },
  { isoCode: 'TN', name: 'Tunisia', region: 'Africa' },
  { isoCode: 'TR', name: 'Turkey', region: 'Asia' },
  { isoCode: 'TM', name: 'Turkmenistan', region: 'Asia' },
  { isoCode: 'TV', name: 'Tuvalu', region: 'Oceania' },
  { isoCode: 'UG', name: 'Uganda', region: 'Africa' },
  { isoCode: 'UA', name: 'Ukraine', region: 'Europe' },
  { isoCode: 'AE', name: 'United Arab Emirates', region: 'Asia' },
  { isoCode: 'GB', name: 'United Kingdom', region: 'Europe' },
  { isoCode: 'US', name: 'United States', region: 'Americas' },
  { isoCode: 'UY', name: 'Uruguay', region: 'Americas' },
  { isoCode: 'UZ', name: 'Uzbekistan', region: 'Asia' },
  { isoCode: 'VU', name: 'Vanuatu', region: 'Oceania' },
  { isoCode: 'VA', name: 'Vatican City', region: 'Europe' },
  { isoCode: 'VE', name: 'Venezuela', region: 'Americas' },
  { isoCode: 'VN', name: 'Vietnam', region: 'Asia' },
  { isoCode: 'YE', name: 'Yemen', region: 'Asia' },
  { isoCode: 'ZM', name: 'Zambia', region: 'Africa' },
  { isoCode: 'ZW', name: 'Zimbabwe', region: 'Africa' },
]
