// Curated songs. Each unlocks its country. Country attribution is recording
// location (the project's chosen ground truth), not artist nationality —
// several of these are deliberately diaspora/expat artists where those differ.
export const songs: { title: string; artist: string; isoCode: string; spotifyTrackId: string }[] = [
  { title: 'Helala', artist: 'Tikoubaouine', isoCode: 'DZ', spotifyTrackId: '7ElvWhLj4ARrSFuykhxqQT' },
  { title: 'The Less I Know The Better', artist: 'Tame Impala', isoCode: 'AU', spotifyTrackId: '6K4t31amVTZDgR3sKmwUJJ' },
  { title: 'Судно (Борис Рыжий)', artist: 'Molchat Doma', isoCode: 'BY', spotifyTrackId: '1SHB1hp6267UK9bJQUxYvO' },
  { title: 'Palco', artist: 'Gilberto Gil', isoCode: 'BR', spotifyTrackId: '2wL88cvKXUOfHuYVd62hji' },
  { title: 'Envolver', artist: 'Anitta', isoCode: 'BR', spotifyTrackId: '3FkeNbs9Zeiqkr3WkbOiGp' },
  { title: 'Speed Racer', artist: 'Fernanda Abreu', isoCode: 'BR', spotifyTrackId: '5kZbymDUiBrZu6QLddJOhL' },
  { title: "Hips Don't Lie (feat. Wyclef Jean)", artist: 'Shakira', isoCode: 'CO', spotifyTrackId: '3d0WouFnFmr0K3kjeza3fF' },
  { title: 'Ayonha', artist: 'Hamid Al Shaeri', isoCode: 'EG', spotifyTrackId: '7j3758mGOPLkd7UQsmbWYg' },
  { title: 'Sabry Aalil', artist: 'Sherine', isoCode: 'EG', spotifyTrackId: '7qLXBcYW78is9LygQBziAU' },
  { title: 'Get Lucky (feat. Pharrell Williams and Nile Rodgers)', artist: 'Daft Punk', isoCode: 'FR', spotifyTrackId: '69kOkLUCkxIZYexIgSG8rq' },
  { title: 'Twer Nyame (Excerpt)', artist: 'Ebo Taylor', isoCode: 'GH', spotifyTrackId: '5NMVCCPd1YVo9CTpGHZ4kt' },
  { title: 'Jai Ho! (You Are My Destiny)', artist: 'A.R. Rahman', isoCode: 'IN', spotifyTrackId: '7Kpqjspw4Y7HrvItIRcBiW' },
  { title: 'Lady Magnolia', artist: 'Piero Umiliani', isoCode: 'IT', spotifyTrackId: '5yEu5YHXKzbBerMRWQyQoR' },
  { title: 'Linda Cançao', artist: 'Barrio Jazz Gang', isoCode: 'IT', spotifyTrackId: '7j9R8UwGYw4Ne76lJN2SO0' },
  { title: 'Three Little Birds', artist: 'Bob Marley & The Wailers', isoCode: 'JM', spotifyTrackId: '7yFvSYKk3g5g8e7Ffl16ws' },
  { title: 'PONPONPON', artist: 'Kyary Pamyu Pamyu', isoCode: 'JP', spotifyTrackId: '1c6C2wg7PRbPBRRUaEvheC' },
  { title: 'Dynamite', artist: 'BTS', isoCode: 'KR', spotifyTrackId: '5QDLhrAOJJdNAmCTJ8xMyW' },
  { title: 'Gelty', artist: 'Ahmed Fakroun', isoCode: 'LY', spotifyTrackId: '6haHoWRck06kZn4h92sEeL' },
  { title: 'Sabbar', artist: 'El Shab Arab', isoCode: 'MA', spotifyTrackId: '6UKDNeXybtfbfTJrLViBRo' },
  { title: 'Come On Home', artist: 'The Lijadu Sisters', isoCode: 'NG', spotifyTrackId: '2NIIJ5WfrK4ANNPHcOhSeb' },
  { title: 'Essence (feat. Tems)', artist: 'Wizkid', isoCode: 'NG', spotifyTrackId: '5FG7Tl93LdH117jEKYl3Cm' },
  { title: 'Water No Get Enemy', artist: 'Fela Kuti', isoCode: 'NG', spotifyTrackId: '4YZv78tF4qCI841KHRF3vf' },
  { title: 'Baayo (Hey Woman)', artist: 'Mukhtar Ramadan Idii', isoCode: 'SO', spotifyTrackId: '1BtgXYAivS7tTiSeEXDzId' },
  { title: 'Daraadaa Muxibo (Because of You Muxibo)', artist: 'Dur-Dur Band', isoCode: 'SO', spotifyTrackId: '7z3IXBX6iCylFrG33nuGDe' },
  { title: 'Dancing Queen', artist: 'ABBA', isoCode: 'SE', spotifyTrackId: '0GjEhVFGZW8afUYGChu3Rr' },
  { title: 'Summum Bonum', artist: '落日飛車 Sunset Rollercoaster', isoCode: 'TW', spotifyTrackId: '3ekzhkbrcqwY806Rgkb8k1' },
  { title: 'Şoför Bey', artist: 'Altin Gün', isoCode: 'TR', spotifyTrackId: '47Hka9URh3i0SQuCKfoJls' },
  { title: 'Never Gonna Give You Up', artist: 'Rick Astley', isoCode: 'GB', spotifyTrackId: '4uLU6hMCjMI75M1A2tKUQC' },
  { title: 'Cissy Strut', artist: 'The Meters', isoCode: 'US', spotifyTrackId: '0WSlOSMLJWoWUpWci9nnRb' },
]
