// Curated songs. Each unlocks its country. Country attribution is recording
// location (the project's chosen ground truth), not artist nationality —
// several of these are deliberately diaspora/expat artists where those differ.
// A few are deliberate exceptions where the curator chose artist heritage
// over recording location: Tito Puente's "Oye Como Va" (Puerto Rico), The
// Scorpios' "Mashena: We Went" (Sudan, despite being recorded at Abbey Road
// in London), Mayra Andrade's "Afeto" (Cape Verde, despite the "Manga" album
// being recorded in Paris/Abidjan), Bebe Manga's "Lokognolo" (Cameroon,
// despite "Ami-Oyomiya" being recorded in Paris), and Enigma's "Sadeness"
// (Germany, Michael Cretu's home base, despite being recorded in Ibiza).
export const songs: { title: string; artist: string; isoCode: string; spotifyTrackId: string }[] = [
  { title: "Don't Know What's Normal", artist: 'Shintaro Sakamoto', isoCode: 'JP', spotifyTrackId: '6nF10SdhHFoplBPcynWYcI' },
  { title: 'Ayonha', artist: 'Hamid Al Shaeri', isoCode: 'EG', spotifyTrackId: '7j3758mGOPLkd7UQsmbWYg' },
  { title: 'Судно (Борис Рыжий)', artist: 'Molchat Doma', isoCode: 'BY', spotifyTrackId: '1SHB1hp6267UK9bJQUxYvO' },
  { title: 'Daraadaa Muxibo (Because of You Muxibo)', artist: 'Dur-Dur Band', isoCode: 'SO', spotifyTrackId: '7z3IXBX6iCylFrG33nuGDe' },
  { title: 'Baayo (Hey Woman)', artist: 'Mukhtar Ramadan Idii', isoCode: 'SO', spotifyTrackId: '1BtgXYAivS7tTiSeEXDzId' },
  { title: 'Afe Ato Yen Bio', artist: 'De Frank Kakra', isoCode: 'GH', spotifyTrackId: '6Fo4aloJ4ee81jfnFYGw2N' },
  { title: 'Summum Bonum', artist: '落日飛車 Sunset Rollercoaster', isoCode: 'TW', spotifyTrackId: '3ekzhkbrcqwY806Rgkb8k1' },
  { title: 'Şoför Bey', artist: 'Altin Gün', isoCode: 'TR', spotifyTrackId: '47Hka9URh3i0SQuCKfoJls' },
  { title: 'Speed Racer', artist: 'Fernanda Abreu', isoCode: 'BR', spotifyTrackId: '5kZbymDUiBrZu6QLddJOhL' },
  { title: 'Cissy Strut', artist: 'The Meters', isoCode: 'US', spotifyTrackId: '0WSlOSMLJWoWUpWci9nnRb' },
  { title: 'Gelty', artist: 'Ahmed Fakroun', isoCode: 'LY', spotifyTrackId: '6haHoWRck06kZn4h92sEeL' },
  { title: 'Helala', artist: 'Tikoubaouine', isoCode: 'DZ', spotifyTrackId: '7ElvWhLj4ARrSFuykhxqQT' },
  { title: 'Come On Home', artist: 'The Lijadu Sisters', isoCode: 'NG', spotifyTrackId: '2NIIJ5WfrK4ANNPHcOhSeb' },
  { title: 'Lady Magnolia', artist: 'Piero Umiliani', isoCode: 'IT', spotifyTrackId: '5yEu5YHXKzbBerMRWQyQoR' },
  { title: 'Sabbar', artist: 'El Shab Arab', isoCode: 'MA', spotifyTrackId: '6UKDNeXybtfbfTJrLViBRo' },
  { title: 'Water No Get Enemy', artist: 'Fela Kuti', isoCode: 'NG', spotifyTrackId: '4YZv78tF4qCI841KHRF3vf' },
  { title: 'Palco', artist: 'Gilberto Gil', isoCode: 'BR', spotifyTrackId: '2wL88cvKXUOfHuYVd62hji' },
  { title: 'Sabry Aalil', artist: 'Sherine', isoCode: 'EG', spotifyTrackId: '7qLXBcYW78is9LygQBziAU' },
  { title: 'Twer Nyame', artist: 'Ebo Taylor', isoCode: 'GH', spotifyTrackId: '3BVfLT91b97GrXhjxYduoz' },
  { title: 'Linda Cançao', artist: 'Barrio Jazz Gang', isoCode: 'IT', spotifyTrackId: '7j9R8UwGYw4Ne76lJN2SO0' },
  { title: 'Tamlalte', artist: 'TASUTA N-IMAL', isoCode: 'MA', spotifyTrackId: '6uox8yoaceLl0NeRlCaZLO' },
  { title: 'Tiga Kurira', artist: 'Rift Valley Brothers', isoCode: 'KE', spotifyTrackId: '3efDQxopuBad4lo9KrLclp' },
  { title: 'Sintayehu', artist: 'Hailu Mergia, Dahlak Band', isoCode: 'ET', spotifyTrackId: '2wMmUvfrkpFJ4ovjpMNVmL' },
  { title: 'Al Asafir', artist: 'Kamal Keila', isoCode: 'SD', spotifyTrackId: '5e2FVads2DgfwG3oDJt0qS' },
  { title: 'Kilário', artist: 'Felipe El, Di Melo', isoCode: 'BR', spotifyTrackId: '5OE9nZgCGZEoAkdC478sfK' },
  { title: 'Kamusale', artist: 'WITCH', isoCode: 'ZM', spotifyTrackId: '5jZ7v5gwgw59Glhqm32623' },
  { title: 'Best Woman', artist: 'Vincent Ahehehinnou', isoCode: 'BJ', spotifyTrackId: '3gRX7NPAeNolvP39gdnCXc' },
  { title: 'Nile Waves', artist: 'The Scorpions, Saif Abu Bakr', isoCode: 'SD', spotifyTrackId: '6fvKQ1tPJWdFSwPybA2dag' },
  { title: "Love Don't Live Here Any More", artist: 'Sharon Forrester', isoCode: 'JM', spotifyTrackId: '7CJE1bufEvU7relk1R4bXu' },
  { title: 'Хочу перемен', artist: 'Kino', isoCode: 'RU', spotifyTrackId: '1f7YBz1mbr8EnFSiOoCEd2' },
  { title: 'Фильмы', artist: 'Molchat Doma', isoCode: 'BY', spotifyTrackId: '7kbaxgNp1qk2rdNoNLusgt' },
  { title: 'Mahè', artist: 'Piero Umiliani', isoCode: 'IT', spotifyTrackId: '29eLonNk3JNVWqu58cr7rq' },
  { title: 'Shake Hands', artist: 'Geraldo Pino', isoCode: 'SL', spotifyTrackId: '2hyyRdPCPQNzb70q7BDgkz' },
  { title: 'Alteleyeshegnem', artist: 'Alemayehu Eshete', isoCode: 'ET', spotifyTrackId: '547fHlns6D8pUibw6C1sJd' },
  { title: "Dancin'", artist: 'Bro David', isoCode: 'BZ', spotifyTrackId: '54p4jGEXMPszK7hkLonrvB' },
  { title: 'Tihilele', artist: 'Les Filles de Illighadad', isoCode: 'NE', spotifyTrackId: '33TrNiUF7Q2DYmTgfFfQTk' },
  { title: 'Floated By', artist: 'Peter Cat Recording Co.', isoCode: 'IN', spotifyTrackId: '7IAKxhI1z8Sas7iLcX8YF5' },
  { title: 'Airxinii shog', artist: 'Tserendavaa, Tsogtgerel', isoCode: 'MN', spotifyTrackId: '0tUuftTiw8PxpanpGKGY6x' },
  { title: 'Wahdi Ana', artist: 'Melhem Barakat', isoCode: 'LB', spotifyTrackId: '3u0ax2jYp3zGM01A4Gfndi' },
  { title: 'Live in Other World', artist: 'Itadi', isoCode: 'TG', spotifyTrackId: '27nIOL9zT7Ltsbf9hxAMdQ' },
  { title: 'Alech', artist: 'Dalton', isoCode: 'TN', spotifyTrackId: '6OJo63o4YdJmvrgzrNQSX7' },
  { title: 'Mahlalela', artist: 'Letta Mbulu, Hugh Masekela', isoCode: 'ZA', spotifyTrackId: '30qQIKaWcWn5U5h724YDDv' },
  { title: 'Be Ni Son', artist: 'Les Amazones de Guinée', isoCode: 'GN', spotifyTrackId: '164vDekfkC0HaUanJvVEQX' },
  { title: 'Argos Farfish', artist: 'Sharhabil Ahmed', isoCode: 'SD', spotifyTrackId: '5VHD0OAEcSpThoP02AlYQw' },
  { title: 'Adome Nyueto', artist: 'Yta Jourias', isoCode: 'TG', spotifyTrackId: '4JxUuQvXNpSWOZloyLpqVU' },
  { title: 'More Women', artist: 'Saâda Bonaire', isoCode: 'DE', spotifyTrackId: '73R5rWJMt6zzgiwLzOYfWR' },
  { title: 'Volando Voy', artist: 'Camaron De La Isla', isoCode: 'ES', spotifyTrackId: '6SerGmTEZrl5XoVdYV4QKG' },
  { title: 'Mambo No 5', artist: 'Pérez Prado', isoCode: 'CU', spotifyTrackId: '6fJnlY8rYqC37J2u2OeEMf' },
  { title: 'Pachuco Bailarín', artist: 'Ramon Marquez', isoCode: 'MX', spotifyTrackId: '3exgmEwgSaqw6K1gez1wTM' },
  { title: 'Oye Cómo Va', artist: 'Tito Puente', isoCode: 'PR', spotifyTrackId: '73uEbChpBB29ttwVnwuNVE' },
  { title: 'Sadeness', artist: 'Enigma', isoCode: 'DE', spotifyTrackId: '1POdxGN4pDCh9enCeR6Rae' },
  { title: "Histoire d'1 soir - Bye bye les galères", artist: 'Bibi Flash', isoCode: 'FR', spotifyTrackId: '03QgO3lV2SxLD2rrdetFHt' },
  { title: "Autopsie d'un complot", artist: 'Ahmed Malek', isoCode: 'DZ', spotifyTrackId: '0nJPzwRclRWEniqHGQxdUv' },
  { title: 'Mudzimu Ndiringe', artist: 'Hallelujah Chicken Run Band', isoCode: 'ZW', spotifyTrackId: '4lngVAMhWO9OhbAv5AHocG' },
  { title: 'Mashena: We Went', artist: 'The Scorpios', isoCode: 'SD', spotifyTrackId: '7t10EPIERFazJEhHFjE0C8' },
  { title: 'Alalaké', artist: 'Bembeya Jazz National', isoCode: 'GN', spotifyTrackId: '6b5s2fQ7iVf41x3FI88fcz' },
  { title: 'Ansumana', artist: 'Susso', isoCode: 'GM', spotifyTrackId: '0uqakDnNhgHf7WFj4wqpM3' },
  { title: 'Ya Bismillah', artist: 'Mamman Sani', isoCode: 'NE', spotifyTrackId: '1zFU01tSdPAgBTXGbkzfrc' },
  { title: 'Coq a counula', artist: 'Erick Cosaque', isoCode: 'GP', spotifyTrackId: '0Q1bHQqoS5vVxDUIkgSroI' },
  { title: 'Lokognolo', artist: 'Bebe Manga', isoCode: 'CM', spotifyTrackId: '1kGgfMfE884VVKc1q4sa4t' },
  { title: 'Morning', artist: 'Azymuth', isoCode: 'BR', spotifyTrackId: '6Pr8fOfppj8C6qpkAYDDzE' },
  { title: 'Afeto', artist: 'Mayra Andrade', isoCode: 'CV', spotifyTrackId: '6Y9ajxGefBUK9pMbT0C8gv' },
  { title: 'A Buena Vista', artist: 'Soneros De Verdad', isoCode: 'CU', spotifyTrackId: '4stihUnPsFTrG7IOmtFZWj' },
  { title: 'Oriente', artist: 'Asere', isoCode: 'CU', spotifyTrackId: '4GeGB90DoeY5CWpVQyGymM' },
  { title: 'Patria Querida', artist: 'Los Guaracheros De Oriente', isoCode: 'CU', spotifyTrackId: '6hGfBBs2yvBcMbfTMsARGx' },
  { title: 'Me siento loco', artist: 'Los Yetis', isoCode: 'CO', spotifyTrackId: '2VrEC8COwvsWqIRe7slj41' },
  { title: 'Ya Se Ha Muerto Mi Abuelo', artist: 'Juaneco Y Su Combo', isoCode: 'PE', spotifyTrackId: '01coR52VHa06J1DnMkls29' },
  { title: 'Tiene Sabor (feat. Omara Portuondo)', artist: 'Buena Vista Social Club, Omara Portuondo', isoCode: 'CU', spotifyTrackId: '659r0xM5pXvb5sUQG3Yl28' },
  { title: 'La Colegiala', artist: 'Rodolfo y su Típica RA7', isoCode: 'CO', spotifyTrackId: '5XyfJqyQbBXiZtG98a8RBY' },
  { title: 'Silbando', artist: 'Los Ribereños', isoCode: 'PE', spotifyTrackId: '6sZi6zDRc7YaUf3WsmwDN7' },
  { title: 'Lobos al Escape', artist: 'Los Orientales de Paramonga', isoCode: 'PE', spotifyTrackId: '2UMTGUu66hP2dW3rvQJIgL' },
  { title: 'Ni Piedra Ni Madera', artist: 'Internacional Carro Show', isoCode: 'MX', spotifyTrackId: '72J3e5bqMBOX4jdaT1vsUj' },
]
